# Generated by Django 4.1.7 on 2023-05-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_alter_profile_batch_alter_profile_sem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
