# Generated by Django 4.2 on 2023-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('clg', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('cid', models.CharField(max_length=20)),
                ('sem', models.IntegerField()),
                ('batch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register_Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('addr', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Register_Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('pas', models.CharField(max_length=20)),
                ('cpas', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
