# Generated by Django 4.2 on 2023-04-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_forms_alter_register_edu_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('addr', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Forms',
        ),
        migrations.DeleteModel(
            name='Register_Edu',
        ),
        migrations.DeleteModel(
            name='Register_Personal',
        ),
        migrations.DeleteModel(
            name='Register_Security',
        ),
    ]
