# Generated by Django 4.2 on 2023-04-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_personal_delete_forms_delete_register_edu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='dist',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='state',
        ),
    ]
