# Generated by Django 4.2 on 2023-04-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_personal_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='addr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='dist',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='gender',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
