# Generated by Django 4.2 on 2023-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_personal_addr_personal_dist_personal_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
