# Generated by Django 4.2 on 2023-04-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_personal_email_personal_phone_personal_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120, null=True)),
                ('clg', models.CharField(max_length=20, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('branch', models.CharField(max_length=20, null=True)),
                ('cid', models.CharField(max_length=20, null=True)),
                ('sem', models.IntegerField(null=True)),
                ('batch', models.IntegerField(null=True)),
            ],
        ),
    ]
