# Generated by Django 4.2 on 2023-04-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120, null=True)),
                ('pas', models.CharField(max_length=20, null=True)),
                ('cpas', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
