# Generated by Django 4.1.7 on 2023-04-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='lname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='mname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
