# Generated by Django 4.2 on 2023-04-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_personal_fname_alter_personal_lname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
